spring:
  datasource:
    url: "jdbc:h2:mem:filmorate;MODE=PostgreSQL;"
    url2: "jdbc:h2:file:./db/filmorate;MODE=PostgreSQL;"
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      max-lifetime: 30000
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 5
  h2:
    console:
      enabled: true
      path: /h2-console