spring:
  datasource:
    url: "jdbc:h2:mem:filmorate;MODE=PostgreSQL;"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    validate-on-migrate: true
  h2:
    console:
      enabled: true
      path: /h2-console